---
- name: Update and Upgrade APT Packages
  hosts: all
  become: yes
  become_method: sudo
  #become_user: root
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      tags:
        - update

    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
      tags:
        - upgrade

    - name: Clean package cache
      apt:
        autoclean: yes
      tags:
        - cleanup
