---
- hosts: all
  become: yes
  tasks:
  
    - name: Stop unattended-upgrades service  
    ansible.builtin.service:  
      name: unattended-upgrades  
      state: stopped  
      enabled: no  # Disable auto-start temporarily  

    - name: Update apt cache
      apt: update_cache=yes

    - name: Upgrade all packages
      apt: upgrade=dist

    - name: Auto-remove unused packages
      apt: autoremove=yes

    - name: Restart unattended-upgrades service  
    ansible.builtin.service:  
      name: unattended-upgrades  
      state: started  
      enabled: yes 

    - name: Reboot if necessary
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
